### ISSUE TITLE
Error: Enable splunk boot-start via systemd failing

### ISSUE THREAD

**Issue by morufajibike** [splunk/ansible-role-for-splunk#105]
The [configure_splunk_boot.yml ](https://github.com/splunk/ansible-role-for-splunk/blob/master/roles/splunk/tasks/configure_splunk_boot.yml#L75) playbook fails with the error below for a new VM:

`fatal: [lm-host]: FAILED! => {"changed": true, "cmd": ["/srv/splunk/splunk/bin/splunk", "enable", "boot-start", "-user", "splunk", "-systemd-managed", "1", "--answer-yes", "--auto-ports", "--no-prompt", "--accept-license"], "delta": "0:00:00.890923", "end": "2021-10-06 15:42:54.740175", "msg": "non-zero return code", "rc": 4, "start": "2021-10-06 15:42:53.849252", "stderr": "Copying '/srv/splunk/splunk/etc/openldap/ldap.conf.default' to '/srv/splunk/splunk/etc/openldap/ldap.conf'.\nbtool returned something in stderr: 'Couldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied\nCouldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied\nCouldn't open \"/srv/splunk/splunk/etc/splunk-launch.conf\": Permission denied\ncouldn't run \"(null)/bin/splunkd\" \"btool\": Permission denied\n'\nCouldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied\nCouldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied\nCouldn't open \"/srv/splunk/splunk/etc/splunk-launch.conf\": Permission denied\n\n\nAn error occurred: Could not create audit keys (returned 8).\nFirst-time run failed!", "stderr_lines": ["Copying '/srv/splunk/splunk/etc/openldap/ldap.conf.default' to '/srv/splunk/splunk/etc/openldap/ldap.conf'.", "btool returned something in stderr: 'Couldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied", "Couldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied", "Couldn't open \"/srv/splunk/splunk/etc/splunk-launch.conf\": Permission denied", "couldn't run \"(null)/bin/splunkd\" \"btool\": Permission denied", "'", "Couldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied", "Couldn't open \"/srv/splunk/splunk/bin/../etc/splunk-launch.conf\": Permission denied", "Couldn't open \"/srv/splunk/splunk/etc/splunk-launch.conf\": Permission denied", "", "", "An error occurred: Could not create audit keys (returned 8).", "First-time run failed!"], "stdout": "ERROR: Couldn't read \"/srv/splunk/splunk/etc/splunk-launch.conf\" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?\n\nThis appears to be your first time running this version of Splunk.", "stdout_lines": ["ERROR: Couldn't read \"/srv/splunk/splunk/etc/splunk-launch.conf\" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?", "", "This appears to be your first time running this version of Splunk."]}`

Any thoughts on what the problem or how it can be fixed?

**Comment by karbovski** [comment]
@morufajibike How did you solve this issue?

**Comment by karbovski** [comment]
I did successfully solved this problem by running this command since it was the problem with permissions.
`chmod -R ug+rwX /opt/splunk`
