### ISSUE TITLE
Conflicting Host Groups "Indexer" vs "Indexers"

### ISSUE THREAD

**Issue by arcsector** [splunk/ansible-role-for-splunk#123]
# Summary

This issue documents a few places where the group "indexers" is referenced but the host group, per the readme and several other locations in the code, is supposed to be `indexer`.

## Problem Details

Here are the places the host group `indexer` is referenced:
- `roles/splunk/tasks/adhoc_decom_indexer.yml:7:  when: "'indexer' in group_names"`
- `README.md`
- `playbooks/splunk_upgrade_full_stack.yml:48:     - indexer`

Here are the places where the host group `indexers` is referenced:
- `playbooks/splunk_idxc_deploy.yml:5:    - indexers`
- `playbooks/splunk_idxc_deploy.yml:19:    - indexers`

## Proposed Solution

Convert all these instances of `indexers` to conform to the `indexer` group set by the README. I will open a PR for this.

**Comment by dtwersky** [comment]
Feel free to open a PR for it

**Comment by arcsector** [comment]
Done - created #124
