### ISSUE TITLE
Documentation: Heavy Forwarder

### ISSUE THREAD

**Issue by cesar-ayuuk** [splunk/ansible-role-for-splunk#141]
Documentation says:

It supports all Splunk deployment roles (Universal Forwarder, Heavy Forwarder, Indexer, Search Head, Deployment Server, Cluster Master, SHC Deployer, DMC, License Master) as well as management of all apps and configurations.

Then

The following group names are currently supported (I don't see the heavyforwarder group in the list ):

full
uf
clustermanager
deploymentserver
indexer
licensemaster
search
shdeployer
dmc

In the inventory.yml there is also an example of a group called heavyforwarder.

I apologize for the confusion or if I'm not understanding the doc fully but I just need a clarification on how the heavy forwarder deployment should be implemented?

**Comment by dtwersky** [comment]
@cesar-ayuuk full == heavyforwarder, as in full installation
