### ISSUE TITLE
splunk_nix_group not assigned as primary in install_splunk.yml

### ISSUE THREAD

**Issue by lzannettacci** [splunk/ansible-role-for-splunk#163]
Hello,

Just found out that when creating the splunk user (splunk_nix_user) the parameter "groups" is used which adds the splunk_nix_user to the splunk_nix_group but does not make that group primary. Using the parameter "group" would make the group primary.
Since install_splunk.yml is called only for fresh installs I would have assumed the group to be primary.

**Comment by jewnix** [comment]
That issue has already been resolved in [this](https://github.com/splunk/ansible-role-for-splunk/pull/148/commits/46e8629f8cc800381a299cda8a5f7e6cfdcbcef7) commit a few months back.

Pull the recent changes and try again
