### ISSUE TITLE
UF Service Restart

### ISSUE THREAD

**Issue by ForsetiJan** [splunk/ansible-role-for-splunk#20]
When installing the UF or an app to it the roles notifies the restart splunk handler. However, since the service is called splunkforwarder rather than Splunkd the restart fails.

I suggest we move the service name to a variable based on the group membership.

**Comment by mason-splunk** [comment]
Good catch. We'll get this fixed today.

**Comment by mason-splunk** [comment]
Resolved in v1.1.0 release. Please update to the latest version as we have fixed this. More info: https://github.com/splunk/ansible-role-for-splunk/releases/tag/v1.1.0
