### ISSUE TITLE
Question about app deployment/sync

### ISSUE THREAD

**Issue by CNScott** [splunk/ansible-role-for-splunk#201]
I see there are options for app_relative_path and splunk_app_deploy_path. I'm assuming those are for the apps to push to search heads and indexers and then the deploy_path is for deployment-apps on the deployer. What if you have different apps on search heads than indexers? For instance some apps documentations recommends them to be installed on search head but not indexer.

What would the github layout need to look like is it just...
```
/apps
   app1
   app2

/deployment-apps
   app1
   app2 
```

Or are the etc folders needed to specify which apps should be where?

```
/apps
  /shcluster/apps
     app1
     app2
  /manager-apps
     app1
     app2
  /deployment-apps
     app1
     app2
```

**Comment by arcsector** [comment]
Hi, I solved this using the `git_version` option, which allows you to specify a branch or tag to pull down. I then pushed all my apps to Github using a branch naming scheme that identified the app as being pulled down to the Cluster Master `idx`, SHDeployer `shc`, or Deployment Server `uf`, and then set the `git_version` var in my `group_vars` for each respective class.

**Comment by CNScott** [comment]
That makes sense. I haven't switched to these playbooks yet. I built a few but it uses splunk's structure to push the apps like /etc/deployment-apps, /etc/manager-apps, /etc/shcluster/apps. But right now it means having 3 copies of each app in the repo so  it needs work. We do have some non-app playbooks that get pushed like syslog-ng config. I'll try this out, thank you!
