### ISSUE TITLE
Upgrade disables bootstart and does not enable after upgrade. 

### ISSUE THREAD

**Issue by Hodgegoblin** [splunk/ansible-role-for-splunk#6]
When running splunk_upgrade_full_stack.yml the task upgrade_splunk.yml disables bootstart and states it will be re-enabled by a handler.  There is no handler that re-enables bootstart.

The task download_and_unarchive.yml notifies the "start splunk" handler after unarchiving the Splunk upgrade.  ~~However, after starting Splunk daemon you are unable to enable bootstart.~~

In looking at the install_splunk.yml task there is a call to configure_splunk_boot.yml.

**Comment by mason-splunk** [comment]
Splunk internal reference: SAS-5320

**Comment by mason-splunk** [comment]
Resolved by PR https://github.com/splunk/ansible-role-for-splunk/pull/8
