### ISSUE TITLE
Enhancement: Install/upgrade from RPM/deb OS packages when compatible with target OS

### ISSUE THREAD

**Issue by splunkenterprisecustomer** [splunk/ansible-role-for-splunk#7]
Hi,

thanks for publishing this ansible role!

We noticed you use the tgz files regardless whether the target OS is supported by splunk's RPM or debian packages.
Would you be open for PR that uses ansible facts for detecting the target OS and use the packages instead of old raw tar files?

We prefer using RPM packages over tgz files whenever OS packages are available.

thanks!

**Comment by mason-splunk** [comment]
@splunkenterprisecustomer  Yes. Would you be contributing this, or are you asking us to develop it?

**Comment by splunkenterprisecustomer** [comment]
Here are the options we see in order of preference (option one would be preferred):

1. you develop it (we are happy to beta test for RPM packages). (If this option is feasible, please let us know if you have a specific timeline in mind.)
2. we contribute it via a pull request and it gets merged upstream into your repo and is maintained by you
3. we develop it and it does not get merged (fork)

Would be great if you could share your thoughts on this.

**Comment by mason-splunk** [comment]
The first option is possible but I can't provide a timeline for it. If you need this functionality sooner than later, I'd recommend submitting a PR for us to review. 

That said, we opted to go with tarballs as they are cross-compatible across different Linux distros (e.g. Ubuntu vs RedHat). The latest version of Splunk is available in the .tgz files, not just .rpm and .deb packages, so I'm not sure what you mean by "old raw tar files".

**Comment by mason-splunk** [comment]
After further consideration, this is not something we will be implementing. The workflows for this role are fairly sophisticated/mature and the risk of breaking functionality in the role by attempting to incorporate RPM/DEB is high, while the ROI is low. 

If you can identify any specific requirements that this role does not meet using TGZ files but are met using RPM/DEB packages, I would be interested in learning more. However, we believe the current implementation using TGZ files is the best one given the information we have today.
