### ISSUE TITLE
Splunk secret installation should happen before accepting the license

### ISSUE THREAD

**Issue by abpetrov** [splunk/ansible-role-for-splunk#80]
During Splunk fresh install, the _splunk_license_accept.yml_ task is called. It creates the initial splunk.secret and the file $SPLUNK_HOME/etc/system/local/server.conf. The server.conf file has the [sslConfig] stanza and sslPassword which is encrypted with the initial splunk.secret.
The task _configure_splunk_secret.yml_ is called afterwards which replaces the initial splunk.secret. However when splunk starts, it will be unable to decrypt the sslPassword, because it was encrypted with the initial splunk.secret, rendering Splunk install broken.

The _configure_splunk_secret.yml_ task should be moved before the _splunk_license_accept.yml_ task.

**Comment by mason-splunk** [comment]
Thanks for the report @abpetrov ! This has been fixed in the v1.4.0 release.
