### ISSUE TITLE
Enhancement: Verify service_ready_flag before running apply shcluster-bundle

### ISSUE THREAD

**Issue by ForsetiJan** [splunk/ansible-role-for-splunk#9]
Toi follow the best practice described [here](https://docs.splunk.com/Documentation/Splunk/8.1.1/DistSearch/PropagateSHCconfigurationchanges#Push_the_configuration_bundle) we should check the service_ready_flag before doing a shcluster-bundle apply.

The challenge we face is that the app repo is synced to the deployer while we need to call the API of one of the search heads to verify the state. Looping the 'search' host group would result in x number of queries which isn't very helpful.

For our situation we created a host group called 'cluster_captain' which holds our preferred captain. I am aware that this isn't a perfect solution but it works.

**Comment by ForsetiJan** [comment]
This assumes that the 'cluster_captain' group only has 1 entry.

`# Note: By using the synchronize module, if the repo already exists on the target host, we are able to only update the diff while preserving the local/ folder
- name: "Synchronize {{ item.app_name }} repo from local Ansible host to {{ splunk_home }}/{{ app_dest }}/{{ item.app_name }} on remote host"
  synchronize:
    src: "{{ app_src }}"
    dest: "{{ splunk_home }}/{{ app_dest }}/"
    recursive: true
    delete: true
    checksum: true
    rsync_opts:
      - "--prune-empty-dirs"
      - "--itemize-changes"
      - "--no-owner"
      - "--no-group"
      - "--no-times"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: appUpdated

- name: Run handler if SHC is ready for it
  shell: "curl -s -u {{ splunk_auth }} -k 'https://{{ captain_hostname }}:8089/services/shcluster/status' -d output_mode=json --get | jq '.entry[].content.captain.service_ready_flag'"
  with_inventory_hostnames:
    - cluster_captain
  loop_control:
    loop_var: captain_hostname
  register: shcstatus
  changed_when: shcstatus.stdout == "true"
  become: true
  args:
    warn: false
  notify: "{{ handler }}"
  when:
    - appUpdated.changed
    - handler == "apply shcluster-bundle"

- name: "If not SHC, call handler directly"  
  debug:
    msg: "Not SHC, calling handler"
  changed_when: true
  notify: "{{ handler }}"
  when:
    - appUpdated.changed
    - handler != "apply shcluster-bundle"`

**Comment by mason-splunk** [comment]
Internal reference: SAS-5372

**Comment by mason-splunk** [comment]
@ForsetiJan Hi there and thank you for this great suggestion! I've implemented it in the v1.0.4 release if you'd like to give it a try. The extra handlers that you had were not necessary in my implementation as the play will now fail if the REST call to a SHC member fails or if the REST call does not return service_ready_state = true, which I believe was the desired intent (i.e. don't perform the deployment to SHC if it's not ready). The only caveat to this approach is that 1) splunk_admin_password needs to be defined (for REST authentication) and 2) you need to tell Ansible which SHC (inventory group) that your deployer manages using the `target_shc_group_name` variable (see README.md). It may be possible to establish this dynamically in the future (eg via REST call on the SH Deployer itself) but for now I believe this solution is adequate. Feel free to shoot me an email for a quicker response: mmorales@splunk.com
