### ISSUE TITLE
Fix hardcoded splunk home path in adhoc_fix_server_certificate.yml

### ISSUE THREAD

**Issue by jeanmichel4121** [splunk/ansible-role-for-splunk#92]
Please could you replace the code below : 

"{{ splunk_home }}/bin/splunk createssl server-cert -d **/opt/splunk**/etc/auth -n server.pem"

With

"{{ splunk_home }}/bin/splunk createssl server-cert -d **{{splunk_home }}**/etc/auth -n server.pem"

it should be more flexible.
Thanks.

**Comment by mason-splunk** [comment]
Will fix hardcoded path in: https://github.com/splunk/ansible-role-for-splunk/search?q=%22%2Fopt%2Fsplunk%2F%22
